#
server:
  port: 8090
  #  servlet:
  #    context-path: practice
  tomcat:
    connection-timeout: 50000

#
spring:
  #springboot2.6.0
  application:
    name: rtbau-service
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  profiles:
  #    active: dev
  #  servlet:
  #    multipart:
  #      max-request-size: 2000MB
  #      max-file-size: 2000MB
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  #  redis:
  #    ##redis
  #    host:
  #    port: 6379
  #    password:
  #    database: 0
  #    ssl: false
  #    redisDirName:
  ##redis
  #cluster:
  #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
  #  commandTimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySql
    url: jdbc:mysql://140.143.185.120:3306/rtbau?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: eamon
    password: Tianc686Tianc
    hikari:
      max-lifetime: 300000 # 不能小于30秒，否则默认回到1800秒
#    druid:
#      # MySql
#      validation-query: select 1
#      # Oracle
#      #validation-query: select 1 from dual
#      validation-query-timeout: 2000
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      stat-view-servlet:
#        enabled: true
#        login-username:
#        login-password:
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
#        session-stat-enable: true
#        session-stat-max-count: 10
  mail:
#    host: smtp.exmail.qq.com
    host: smtp.163.com
    from: xiaominglovejava@163.com
    username: xiaominglovejava
    #    (
    password: HRCOGUMGEYFGCAWB
    protocol: smtp
    default-encoding: UTF-8
    path:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  cloud:
    nacos:
      discovery:
        server-addr: 140.143.185.120:8848
        username: nacos
        password: Tianc686Tianc
        namespace: buzz
# mybatis
mybatis-plus:
  #  mapper-locations: classpath:org/**/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml
  #
  typeAliasesPackage: eamon.daily.practice.**.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    #
    banner: false
    db-config:
      # 0:"1:"2:"4:"UUID", 5:"
      id-type: id_worker
      #
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      #
      table-underline: true
      #
      # Plus
      logic-delete-value: 1
      # Plus
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger
swagger:
  basePackage: eamon.daily.practice
  title: Eamon
  description: Eamon Swagger
  version: 1.0
#  title: BladeX
#  description: BladeX
#  version: 2.6.0.RELEASE
#  license: Powered By BladeX
#  license-url: https://bladex.vip
#  terms-of-service-url: https://bladex.vip
#  contact:
#    name: smallchill
#    email: smallchill@163.com
#    url: https://gitee.com/smallc

GDKey: ae98e8c04a79c7cb62f0db3657cd2508
appToken: AT_fJJCxoV3Qjzl4oVleQ8goJAAvzGiEVFe

langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name:
      log-requests:
      log-responses:


chat:
  url:
  token:
  miniTxt:
  sunoTxt:

wx:
  miniapp:
    configs:
      - appid: wxa2bf88ce6bb9daae
        secret: 5cae7f637066231c9fb30435c79a874c
        msgDataFormat: JSON
    #developer为开发版；trial为体验版；formal为正式版
    miniprogram-state: trial
    air-quality-template-id: hyBA7_Hm8oN82VIf2C_Q22CE1TzPsx75gDN-W_RH1EQ
    weather-template-id: CEkevOTF8AgnxO9kSdJB8KV80yx9wDpbV2lJsGHIgXM
    subscribe-msg-url: https://api.weixin.qq.com/cgi-bin/message/subscribe/send

dubbo:
  application:
    name: dubbo-provider
    version: 1.0.0
  protocol:
    name: dubbo  # dubbo协议
    port: 20880     # -1表示端口从20880开始递增，不会造成端口冲突
  registry:
    address: nacos://140.143.185.120:8848
    parameters:
      namespace: buzz
      username: nacos
      password: Tianc686Tianc
  metadata-report:
    enabled: false
  qos:
    port: 22222




